# Generated by Django 5.0.1 on 2026-01-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
