# Generated by Django 5.0.1 on 2026-01-04 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_address_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
    ]
